# Generated by Django 3.0.8 on 2020-08-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20200805_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='english_name',
        ),
    ]
