# Generated by Django 3.0.7 on 2020-08-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20200808_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldetail',
            name='lat',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='hoteldetail',
            name='lng',
            field=models.CharField(default='', max_length=20),
        ),
    ]
