# Generated by Django 3.0.7 on 2020-08-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20200811_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldetail',
            name='lat',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hoteldetail',
            name='lng',
            field=models.CharField(default='', max_length=255),
        ),
    ]
