# Generated by Django 3.0.8 on 2020-08-07 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='Image',
        ),
    ]
